[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "GHGI-viewer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.30.1,<7"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
matplotlib = ">=3.10.5,<4"
